export const translations = {
  en: {
    auth: { email_verification: "Verify Email", resend_code: "Resend", verify: "Verify", new_account: "New account", apple: "Apple", google: "Google", or: "or", signup: "Sign up", signin: "Sign in", have_account: "Have an account?", no_account: "No account?", signing_in: "Signing in...", creating_account: "Creating account...", invalid_code: "Invalid code", verif_failed: "Verification failed", enter_code: "Enter code sent to your email", invalid_info: "Invalid information", required_fields: "Fill all fields", check_email: "Check your email", weak_password: "Password is too weak", error: "Error", warning: "Warning", success: "Success", clerk_not_loaded: "Auth system not loaded.", network_error: "Network connection lost. Please check your internet.", active_session_redirect: "Active session found. Redirecting...", signin_incomplete: "Sign-in incomplete. Status: ", pass_too_short: "Password is too short. Please enter at least 8 characters.", email_taken: "This email is already in use. Please sign in or try a different address.", invalid_email: "You entered an invalid email address. Please check and try again.", active_signup_exists: "You have a pending sign-up. Try restarting the app.", captcha_error: "Security verification (CAPTCHA) failed.", unknown_error: "An unknown error occurred.", missing_requirements: "Missing requirements:", wrong_code: "The code you entered is invalid.", code_expired: "The verification code has expired.", already_verified_login: "This account is already verified. Please sign in instead.", signup_error: "Sign Up Error" },
    profile: { title: "Profile", info: "Info", name: "Name", username: "Username", email: "Email", cancel: "Cancel", save: "Save", edit: "Edit", signout: "Sign out", language: "Language", update_success: "Profile updated!", update_error: "An error occurred while updating the profile.", success: "Success", error: "Error", signout_confirm_title: "Sign Out", signout_confirm_msg: "Are you sure you want to sign out?", default_username: "User", local_device: "Stored on this device" },
    app: { go_to_date: "Select date", task_deleted: "Deleted", undo: "Undo", overdue_tasks: "Overdue", move_all_today: "Move to today", time_travel: "Time travel", timer: "Reminder", move_tomorrow: "Tomorrow", schedule_tomorrow: "Schedule for tomorrow", delete: "Delete", save: "Save", streak_days: "days!", category: "Category", schedule: "Schedule", permanent_notes: "Permanent Notes", go_to_today: "Today", calendar: "Calendar", write_before_forget: "Don't forget...", scheduled: "Scheduled:", in_1_hour: "1 hour", tonight_21: "21:00", tomorrow_morning: "Morning", next_week: "Next week", uncompleted_tasks: "uncompleted", no_plan: "No excuses, take action.", write_to_dofo: "Don't forget...", scheduled_alert_title: "Scheduled 📅", scheduled_alert_msg: "Task scheduled", permanent_notes_placeholder: "Don't forget...", time_up: "Time's up", mins: "m", hours: "h", days: "d", today: "Today", yesterday: "Yesterday", tomorrow: "Tomorrow", sync_connecting: "Connecting...", sync_loading_tasks: "Loading your tasks...", sync_updating_notes: "Updating notes...", sync_finishing: "Almost there...", sync_done: "Ready!", combo_2: "Nice!", combo_3: "Super!", combo_4: "Great!", combo_5: "Amazing!", combo_6: "Legendary!", first_task_title: "Great!", first_task_subtitle: "First step taken", notification_title: "dofo", notification_body: "Your task is waiting! 🚀", streak_count: "days in a row!", streak_record: "Record: %{count} days 🏆" },
    premium: { title: "dofo Premium", subtitle: "Unlock your full potential.", task_limit_title: "Daily Task Limit Reached", task_limit_msg: "Free plan allows 5 tasks per day. Upgrade to Premium for unlimited tasks.", reminder_title: "Premium Feature", reminder_msg: "Reminders are a Premium feature. Upgrade to unlock.", upgrade: "Upgrade to Premium", restore: "Restore Purchase", restore_not_found: "No previous purchases found.", feature_unlimited: "Unlimited daily tasks", feature_reminders: "Smart reminders & notifications", price: "$4.99 / month", price_yearly: "$39.99 / year", save_badge: "Save 33%", monthly: "Monthly", yearly: "Yearly", get_premium: "Get Premium", already_premium: "You're Premium!", premium_badge: "PREMIUM", free_badge: "FREE", go_premium: "Go Premium", manage_sub: "Manage Subscription", manage_sub_hint: "You can cancel anytime from your store account.", cancel_ios: "To cancel, go to Settings → Apple ID → Subscriptions.", cancel_android: "To cancel, open the Play Store → Account → Subscriptions.", legal_monthly: "$4.99/month. Billed monthly. Price may vary by region.", legal_yearly: "$39.99/year (save 33%). Billed annually. Price may vary by region.", legal_cancel: "Subscriptions auto-renew until cancelled. Cancel at least 24 hours before renewal.", privacy: "Privacy Policy", terms: "Terms of Use", past_reminder_error: "Cannot schedule a reminder in the past.", daily_notif_title: "Ready to finish today strong?", daily_notif_body: "A few tasks remain — knock them out and relax!", weekly_notif_title: "Ready to plan your week?", weekly_notif_body: "A new week starts now. Set your goals and make it count." },
    welcome: { know_this: "Got it", promise: "I promise", give_up: "Skip", continue: "I know, Continue", coward_title: "Giving up?", coward_msg: "Choosing the easy way out.", coward_button: "I won't give up", 
        slide1_title: "Time is Ticking", slide1_subtitle: "Is today another 'I'll do it tomorrow' day? Delay your life, and you'll never be ready.",
        slide2_title: "The Bitter Truth", slide2_subtitle: "90% of people make plans but quit. If giving up is easier, delete this app right now.",
        slide3_title: "No Excuses", slide3_subtitle: "No one is here to baby you. Build a ruthless routine and break your limits.",
        slide4_title: "Are You Ready?", slide4_subtitle: "Step out of a loser's mindset and embrace discipline. Don't waste time if you'll quit."
    },
    quotes: {
        "0": "Today is yours.", "1": "Every day is a fresh start.", "2": "Small steps, big impact.", "3": "Keep going.", "4": "Focus and execute.",
        "5": "You are capable.", "6": "Discipline equals freedom.", "7": "Make it happen.", "8": "Consistency is key.", "9": "Start now."
    }
  },
  tr: {
    auth: { email_verification: "Doğrula", resend_code: "Tekrar gönder", verify: "Doğrula", new_account: "Yeni hesap", apple: "Apple", google: "Google", or: "veya", signup: "Kayıt ol", signin: "Giriş yap", have_account: "Hesabın var mı?", no_account: "Hesabın yok mu?", signing_in: "Giriş yapılıyor...", creating_account: "Hesap oluşturuluyor...", invalid_code: "Geçersiz kod", verif_failed: "Doğrulama başarısız", enter_code: "E-postanıza gelen kodu girin", invalid_info: "Hatalı bilgi", required_fields: "Tüm alanları doldurun", check_email: "E-postanızı kontrol edin", weak_password: "Şifre çok zayıf", error: "Hata", warning: "Uyarı", success: "Başarılı", clerk_not_loaded: "Clerk objesi yüklenmedi.", network_error: "Ağ bağlantısı koptu. Lütfen internetinizi kontrol edin.", active_session_redirect: "Açık oturum tespit edildi. Yönlendiriliyorsunuz...", signin_incomplete: "Hesaba giriş tamamlanamadı. Durum: ", pass_too_short: "Şifreniz çok kısa. Lütfen en az 8 karakter girin.", email_taken: "Bu e-posta adresi zaten kullanılıyor. Giriş yapın veya farklı deneyin.", invalid_email: "Geçersiz e-posta.", active_signup_exists: "Daha önceden tamamlanmamış kaydınız var. Uygulamayı yeniden başlatın.", captcha_error: "CAPTCHA (Güvenlik) hatası.", unknown_error: "Bilinmeyen bir hata oluştu.", missing_requirements: "Dikkat: Ekstra zorunlu alanlar var! Eksikler:", wrong_code: "Girdiğiniz kod geçersiz.", code_expired: "Doğrulama kodunun süresi dolmuş.", already_verified_login: "Bu hesap zaten doğrulandı. Lütfen ana sayfadan giriş yapın.", signup_error: "Kayıt Hatası" },
    profile: { title: "Profil", info: "Bilgiler", name: "Ad Soyad", username: "Kullanıcı Adı", email: "E-posta", cancel: "İptal", save: "Kaydet", edit: "Düzenle", signout: "Çıkış yap", language: "Dil", update_success: "Profil güncellendi!", update_error: "Profil güncellenirken bir hata oluştu.", success: "Başarılı", error: "Hata", signout_confirm_title: "Çıkış Yap", signout_confirm_msg: "Çıkış yapmak istediğinize emin misiniz?", default_username: "Kullanıcı", local_device: "Bu cihazda saklanıyor" },
    app: { go_to_date: "Tarih seç", task_deleted: "Silindi", undo: "Geri al", overdue_tasks: "Gecikenler", move_all_today: "Bugüne taşı", time_travel: "Zamanda gez", timer: "Hatırlatıcı", move_tomorrow: "Yarına aktar", schedule_tomorrow: "Yarın için planla", delete: "Sil", save: "Kaydet", streak_days: "gün!", category: "Kategori", schedule: "Zamanla", permanent_notes: "Kalıcı Notlar", go_to_today: "Bugüne Git", calendar: "Takvim", write_before_forget: "Unutmadan yaz...", scheduled: "Zamanlandı:", in_1_hour: "1 saat", tonight_21: "21:00", tomorrow_morning: "Sabah", next_week: "Haftaya", uncompleted_tasks: "tamamlanmamış görev", no_plan: "Bahane üretme, harekete geç.", write_to_dofo: "Unutmadan yaz...", scheduled_alert_title: "Planlandı 📅", scheduled_alert_msg: "Görev planlandı", permanent_notes_placeholder: "Unutmadan yaz...", time_up: "Süre Doldu", mins: "dk", hours: "sa", days: "g", today: "Bugün", yesterday: "Dün", tomorrow: "Yarın", sync_connecting: "Bağlanılıyor...", sync_loading_tasks: "Görevler yükleniyor...", sync_updating_notes: "Notlar güncelleniyor...", sync_finishing: "Son hazırlıklar...", sync_done: "Hazır!", combo_2: "Güzel!", combo_3: "Süper!", combo_4: "Harika!", combo_5: "Müthiş!", combo_6: "Efsane!", first_task_title: "Harika!", first_task_subtitle: "İlk adım atıldı", notification_title: "dofo", notification_body: "Görevin tamamlanmayı bekliyor! 🚀", streak_count: "gün üst üste!", streak_record: "Rekor: %{count} gün 🏆" },
    premium: { title: "dofo Premium", subtitle: "Tüm potansiyelini ortaya çıkar.", task_limit_title: "Günlük Görev Limitine Ulaştın", task_limit_msg: "Ücretsiz planda günlük 5 görev ekleyebilirsin. Sınırsız görev için Premium'a geç.", reminder_title: "Premium Özellik", reminder_msg: "Hatırlatıcılar Premium özelliğidir. Açmak için Premium'a geç.", upgrade: "Premium'a Geç", restore: "Satın Almayı Geri Yükle", restore_not_found: "Önceki satın alma bulunamadı.", feature_unlimited: "Sınırsız günlük görev", feature_reminders: "Akıllı hatırlatıcılar & bildirimler", price: "₺79.99 / ay", price_yearly: "₺639.99 / yıl", save_badge: "%33 İndirim", monthly: "Aylık", yearly: "Yıllık", get_premium: "Premium'u Al", already_premium: "Premium üyesin!", premium_badge: "PREMİUM", free_badge: "ÜCRETSİZ", go_premium: "Premium'a Geç", manage_sub: "Aboneliği Yönet", manage_sub_hint: "Hesabınızdan istediğiniz zaman iptal edebilirsiniz.", cancel_ios: "İptal için: Ayarlar → Apple ID → Abonelikler.", cancel_android: "İptal için: Play Store → Hesap → Abonelikler.", legal_monthly: "₺79,99/ay. Aylık faturalandırılır.", legal_yearly: "₺639,99/yıl (%33 indirimli). Yıllık faturalandırılır.", legal_cancel: "Abonelikler iptal edilmediği sürece otomatik yenilenir. Yenilemeden en az 24 saat önce iptal edin.", privacy: "Gizlilik Politikası", terms: "Kullanım Koşulları", past_reminder_error: "Geçmiş bir zaman için hatırlatıcı ayarlanamaz.", daily_notif_title: "Bugünü harika bitirmeye ne dersin?", daily_notif_body: "Birkaç görevin kalmış, hemen hallet ve rahatla!", weekly_notif_title: "Haftanı planlamaya hazır mısın?", weekly_notif_body: "Yeni bir hafta başlıyor! Hedeflerini belirle ve harika bir hafta geçir." },
    welcome: { know_this: "Anladım", promise: "Söz veriyorum", give_up: "Pes Etmek İstiyorum", continue: "Bunu Biliyorum, Devam Et", coward_title: "Acizliğin İlanı", coward_msg: "Demek daha başlamadan korkutmayı başardık. Kolay olanı seçip pes ediyorsun.", coward_button: "Haklısın, Korkaklık Etmeyeceğim",
        slide1_title: "Zaman Akıp Gidiyor", slide1_subtitle: 'Bugün de "yarın yaparım" dediğin günlerden biri mi? Hayatını ertelemeye devam edersen, hiçbir zaman hazır olamayacaksın.',
        slide2_title: "Acı Gerçek", slide2_subtitle: "İnsanların %90'ı plan yapar ama ilk zorlukta pes eder. Sıradanlığa teslim olmak senin için daha kolaysa, bu uygulamayı hemen silebilirsin.",
        slide3_title: "Mazeretlere Yer Yok", slide3_subtitle: "Burada seni pohpohlayacak kimse yok. Acıması olmayan bir düzen kurup kendi sınırlarını aşmalısın.",
        slide4_title: "Buna Cidden Hazır mısın?", slide4_subtitle: "Ezik psikolojisinden çıkıp disiplini kucaklıyorsan başla. İki gün sonra sileceksen, hiç vaktimizi alma."
    },
    quotes: {
        "0": "Bugün senin.", "1": "Her gün yeni bir başlangıç.", "2": "Küçük adımlar, büyük etkiler.", "3": "Devam et.", "4": "Odaklan ve uygula.",
        "5": "Yapabilirsin.", "6": "Disiplin özgürlüktür.", "7": "Gerçekleştir.", "8": "İstikrar kilit noktadır.", "9": "Şimdi başla."
    }
  },
  es: {
    auth: { email_verification: "Verificar", resend_code: "Reenviar", verify: "Verificar", new_account: "Nueva cuenta", apple: "Apple", google: "Google", or: "o", signup: "Regístrate", signin: "Entrar", have_account: "¿Tienes cuenta?", no_account: "¿Sin cuenta?", signing_in: "Iniciando...", creating_account: "Creando cuenta...", invalid_code: "Código inválido", verif_failed: "Fallo al verificar", enter_code: "Ingresa el código en tu email", invalid_info: "Info inválida", required_fields: "Completa todo", check_email: "Revisa tu email", weak_password: "La contraseña es muy débil", error: "Error", warning: "Aviso", success: "Éxito", clerk_not_loaded: "Sistema de auth no cargado.", network_error: "Sin conexión de red.", active_session_redirect: "Sesión activa detectada. Redirigiendo...", signin_incomplete: "Inicio incompleto. Estado: ", pass_too_short: "Contraseña muy corta (min. 8).", email_taken: "Email en uso.", invalid_email: "Email inválido.", active_signup_exists: "Registro pendiente encontrado. Reinicia la app.", captcha_error: "Fallo de CAPTCHA.", unknown_error: "Error desconocido.", missing_requirements: "Requisitos faltantes:", wrong_code: "El código es inválido.", code_expired: "El código expiró.", already_verified_login: "Cuenta ya verificada. Inicia sesión.", signup_error: "Error de Registro" },
    profile: { title: "Perfil", info: "Info", name: "Nombre", username: "Usuario", email: "Correo", cancel: "Cancelar", save: "Guardar", edit: "Editar", signout: "Salir", language: "Idioma", update_success: "¡Perfil actualizado!", update_error: "Error al actualizar perfil.", success: "Éxito", error: "Error", signout_confirm_title: "Cerrar sesión", signout_confirm_msg: "¿Seguro que quieres salir?", default_username: "Usuario", local_device: "En este dispositivo" },
    app: { go_to_date: "Fecha", task_deleted: "Eliminado", undo: "Deshacer", overdue_tasks: "Atrasado", move_all_today: "Mover hoy", time_travel: "Viajar", timer: "Recordatorio", move_tomorrow: "Mañana", schedule_tomorrow: "Para mañana", delete: "Borrar", save: "Guardar", streak_days: "días!", category: "Categoría", schedule: "Programar", permanent_notes: "Notas fijas", go_to_today: "Hoy", calendar: "Calendario", write_before_forget: "No olvides...", scheduled: "Prévisto:", in_1_hour: "1 hora", tonight_21: "21:00", tomorrow_morning: "Mañana", next_week: "Otra semana", uncompleted_tasks: "pendientes", no_plan: "Sin excusas, pasa a la acción.", write_to_dofo: "No olvides...", scheduled_alert_title: "Programado 📅", scheduled_alert_msg: "Tarea programada", permanent_notes_placeholder: "No olvides...", time_up: "Tiempo", mins: "m", hours: "h", days: "d", today: "Hoy", yesterday: "Ayer", tomorrow: "Mañana", sync_connecting: "Conectando...", sync_loading_tasks: "Cargando tareas...", sync_updating_notes: "Actualizando notas...", sync_finishing: "Casi listo...", sync_done: "¡Listo!", combo_2: "¡Bien!", combo_3: "¡Genial!", combo_4: "¡Increíble!", combo_5: "¡Asombroso!", combo_6: "¡Legendario!", first_task_title: "¡Genial!", first_task_subtitle: "Primer paso dado", notification_title: "dofo", notification_body: "¡Tu tarea te espera! 🚀", streak_count: "días seguidos", streak_record: "Récord: %{count} días 🏆" },
    premium: { title: "dofo Premium", subtitle: "Desbloquea todo tu potencial.", task_limit_title: "Límite diario alcanzado", task_limit_msg: "El plan gratuito permite 5 tareas al día. Actualiza a Premium.", reminder_title: "Función Premium", reminder_msg: "Los recordatorios son Premium. Actualiza para desbloquear.", upgrade: "Actualizar a Premium", restore: "Restaurar compra", restore_not_found: "No se encontraron compras anteriores.", feature_unlimited: "Tareas ilimitadas", feature_reminders: "Recordatorios inteligentes", price: "$4.99 / mes", price_yearly: "$39.99 / año", save_badge: "33% desc.", monthly: "Mensual", yearly: "Anual", get_premium: "Obtener Premium", already_premium: "¡Eres Premium!", premium_badge: "PREMIUM", free_badge: "GRATIS", go_premium: "Ir Premium", manage_sub: "Administrar suscripción", manage_sub_hint: "Puedes cancelar en cualquier momento desde tu tienda.", cancel_ios: "Para cancelar: Ajustes → Apple ID → Suscripciones.", cancel_android: "Para cancelar: Play Store → Cuenta → Suscripciones.", legal_monthly: "$4.99/mes. Facturado mensualmente.", legal_yearly: "$39.99/año (33% desc.). Facturado anualmente.", legal_cancel: "Las suscripciones se renuevan automáticamente. Cancela 24h antes.", privacy: "Privacidad", terms: "Términos", past_reminder_error: "No se puede programar un recordatorio en el pasado.", daily_notif_title: "¿Listo para terminar el día con fuerza?", daily_notif_body: "Te quedan algunas tareas. ¡Termínalas y descansa!", weekly_notif_title: "¿Listo para planificar tu semana?", weekly_notif_body: "Empieza la semana con metas claras. ¡Hazla memorable!" },
    welcome: { know_this: "Entendido", promise: "Prometo", give_up: "Rendirse", continue: "Continuar", coward_title: "¿Rindiéndose?", coward_msg: "Eligiendo el camino fácil.", coward_button: "No me rendiré",
        slide1_title: "El tiempo pasa", slide1_subtitle: "¿Es hoy otro 'lo haré mañana'? Retrasa tu vida y nunca estarás listo.",
        slide2_title: "La cruda realidad", slide2_subtitle: "El 90% de la gente hace planes y renuncia. Si rendirte es más fácil, borra esta app.",
        slide3_title: "Sin excusas", slide3_subtitle: "Nadie te consentirá aquí. Crea una rutina dura y rompe tus límites.",
        slide4_title: "¿Estás listo?", slide4_subtitle: "Sal de la mente perdedora. No pierdas tiempo si vas a rendirte pronto."
    },
    quotes: {
        "0": "Hoy es tuyo.", "1": "Cada día es un reinicio.", "2": "Pequeños pasos, gran impacto.", "3": "Sigue adelante.", "4": "Enfócate y ejecuta.",
        "5": "Eres capaz.", "6": "La disciplina es libertad.", "7": "Haz que pase.", "8": "La constancia es clave.", "9": "Empieza ahora."
    }
  },
  de: {
    auth: { email_verification: "Bestätigen", resend_code: "Erneut", verify: "Bestätigen", new_account: "Neues Konto", apple: "Apple", google: "Google", or: "oder", signup: "Registrieren", signin: "Anmelden", have_account: "Hast du ein Konto?", no_account: "Kein Konto?", signing_in: "Anmelden...", creating_account: "Erstelle Konto...", invalid_code: "Ungültiger Code", verif_failed: "Verifizierung fehlgeschlagen", enter_code: "Code eingeben", invalid_info: "Ungültige Infos", required_fields: "Alle ausfüllen", check_email: "Prüfe E-Mail", weak_password: "Passwort ist zu schwach", error: "Fehler", warning: "Warnung", success: "Erfolg", clerk_not_loaded: "Auth nicht geladen.", network_error: "Netzwerkverbindung fehlgeschlagen.", active_session_redirect: "Aktive Sitzung. Weiterleitung...", signin_incomplete: "Anmeldung unvollständig. Status: ", pass_too_short: "Passwort ist zu kurz (min 8).", email_taken: "Email wird schon benutzt.", invalid_email: "Ungültige E-Mail.", active_signup_exists: "Offene Registrierung gefunden. Starte App neu.", captcha_error: "CAPTCHA-Fehler.", unknown_error: "Unbekannter Fehler.", missing_requirements: "Fehlende Anforderungen:", wrong_code: "Der Code ist ungültig.", code_expired: "Der Code ist abgelaufen.", already_verified_login: "Konto bereits verifiziert. Bitte anmelden.", signup_error: "Registrierungsfehler" },
    profile: { title: "Profil", info: "Info", name: "Name", username: "Username", email: "E-Mail", cancel: "Abbrechen", save: "Speichern", edit: "Bearbeiten", signout: "Abmelden", language: "Sprache", update_success: "Profil aktualisiert!", update_error: "Fehler beim Aktualisieren.", success: "Erfolg", error: "Fehler", signout_confirm_title: "Abmelden", signout_confirm_msg: "Bist du sicher, dass du dich abmelden willst?", default_username: "Benutzer", local_device: "Auf diesem Gerät gespeichert" },
    app: { go_to_date: "Datum", task_deleted: "Gelöscht", undo: "Rückgängig", overdue_tasks: "Überfällig", move_all_today: "Auf heute", time_travel: "Zeitreise", timer: "Erinnerung", move_tomorrow: "Morgen", schedule_tomorrow: "Für morgen", delete: "Löschen", save: "Speichern", streak_days: "Tage!", category: "Kategorie", schedule: "Planen", permanent_notes: "Feste Notizen", go_to_today: "Heute", calendar: "Kalender", write_before_forget: "Vergiss nicht...", scheduled: "Geplant:", in_1_hour: "1 Std.", tonight_21: "21:00", tomorrow_morning: "Morgen", next_week: "Nächste Woche", uncompleted_tasks: "unerledigte", no_plan: "Keine Ausreden, werde aktiv.", write_to_dofo: "Vergiss nicht...", scheduled_alert_title: "Geplant 📅", scheduled_alert_msg: "Aufgabe geplant", permanent_notes_placeholder: "Vergiss nicht...", time_up: "Zeit abgelaufen", mins: "m", hours: "h", days: "t", today: "Heute", yesterday: "Gestern", tomorrow: "Morgen", sync_connecting: "Verbinden...", sync_loading_tasks: "Aufgaben laden...", sync_updating_notes: "Notizen aktualisieren...", sync_finishing: "Fast fertig...", sync_done: "Fertig!", combo_2: "Schön!", combo_3: "Super!", combo_4: "Großartig!", combo_5: "Fantastisch!", combo_6: "Legendär!", first_task_title: "Großartig!", first_task_subtitle: "Erster Schritt getan", notification_title: "dofo", notification_body: "Deine Aufgabe wartet! 🚀", streak_count: "Tage in Folge!", streak_record: "Rekord: %{count} Tage 🏆" },
    premium: { title: "dofo Premium", subtitle: "Entfalte dein volles Potenzial.", task_limit_title: "Tageslimit erreicht", task_limit_msg: "Kostenlos: 5 Aufgaben pro Tag. Upgrade für unbegrenzte Aufgaben.", reminder_title: "Premium-Funktion", reminder_msg: "Erinnerungen sind Premium. Upgrade zum Freischalten.", upgrade: "Auf Premium upgraden", restore: "Kauf wiederherstellen", restore_not_found: "Keine früheren Käufe gefunden.", feature_unlimited: "Unbegrenzte Aufgaben", feature_reminders: "Smarte Erinnerungen", price: "4,99 € / Monat", price_yearly: "39,99 € / Jahr", save_badge: "33% sparen", monthly: "Monatlich", yearly: "Jährlich", get_premium: "Premium holen", already_premium: "Du bist Premium!", premium_badge: "PREMIUM", free_badge: "GRATIS", go_premium: "Premium", manage_sub: "Abo verwalten", manage_sub_hint: "Du kannst jederzeit über deinen Store kündigen.", cancel_ios: "Kündigen: Einstellungen → Apple ID → Abos.", cancel_android: "Kündigen: Play Store → Konto → Abos.", legal_monthly: "4,99 €/Monat. Monatlich abgerechnet.", legal_yearly: "39,99 €/Jahr (33% sparen). Jährlich abgerechnet.", legal_cancel: "Abos verlängern sich automatisch. Bitte 24 Std. vorher kündigen.", privacy: "Datenschutz", terms: "Nutzungsbedingungen", past_reminder_error: "Eine Erinnerung in der Vergangenheit kann nicht geplant werden.", daily_notif_title: "Bereit, den Tag stark zu beenden?", daily_notif_body: "Ein paar Aufgaben warten — erledige sie und entspanne!", weekly_notif_title: "Bereit, deine Woche zu planen?", weekly_notif_body: "Eine neue Woche beginnt! Setze deine Ziele und mach sie unvergesslich." },
    welcome: { know_this: "Verstanden", promise: "Versprochen", give_up: "Aufgeben", continue: "Weiter", coward_title: "Aufgeben?", coward_msg: "Den einfachen Weg wählen.", coward_button: "Ich gebe nicht auf",
        slide1_title: "Die Zeit läuft", slide1_subtitle: "Ist heute wieder ein 'Morgen'-Tag? Verzögere dein Leben und du wirst nie bereit sein.",
        slide2_title: "Die bittere Wahrheit", slide2_subtitle: "90% geben auf. Wenn Aufgeben einfacher ist, lösche die App.",
        slide3_title: "Keine Ausreden", slide3_subtitle: "Niemand verzärtelt dich hier. Erstelle eine rücksichtslose Routine.",
        slide4_title: "Bist du bereit?", slide4_subtitle: "Verlass das Verlierer-Denken. Verschwende keine Zeit, wenn du aufgibst."
    },
    quotes: {
        "0": "Heute gehört dir.", "1": "Jeder Tag ist ein Neuanfang.", "2": "Kleine Schritte, große Wirkung.", "3": "Mach weiter.", "4": "Fokus und Ausführung.",
        "5": "Du kannst das.", "6": "Disziplin ist Freiheit.", "7": "Mach es wahr.", "8": "Beständigkeit ist der Schlüssel.", "9": "Fange jetzt an."
    }
  },
  fr: {
    auth: { email_verification: "Vérifier", resend_code: "Renvoyer", verify: "Vérifier", new_account: "Nouveau", apple: "Apple", google: "Google", or: "ou", signup: "S'inscrire", signin: "Se connecter", have_account: "Déjà un compte?", no_account: "Pas de compte?", signing_in: "Connexion...", creating_account: "Création en cours...", invalid_code: "Code invalide", verif_failed: "Échec vérif", enter_code: "Entrez le code", invalid_info: "Infos non valides", required_fields: "Remplir tous", check_email: "Vérifiez vos e-mails", weak_password: "Mot de passe faible", error: "Erreur", warning: "Attention", success: "Succès", clerk_not_loaded: "Erreur système auth.", network_error: "Connexion réseau perdue.", active_session_redirect: "Session active. Redirection...", signin_incomplete: "Connexion incomplète. Statut: ", pass_too_short: "Mot de passe trop court (min 8).", email_taken: "Email déjà utilisé.", invalid_email: "Email invalide.", active_signup_exists: "Inscription en cours. Redémarrez l'appli.", captcha_error: "Erreur CAPTCHA.", unknown_error: "Erreur inconnue.", missing_requirements: "Exigences manquantes:", wrong_code: "Code invalide.", code_expired: "Le code a expiré.", already_verified_login: "Compte déjà vérifié. Veuillez vous connecter.", signup_error: "Erreur d'inscription" },
    profile: { title: "Profil", info: "Infos", name: "Nom", username: "Nom d'utilisateur", email: "E-mail", cancel: "Annuler", save: "Sauver", edit: "Modifier", signout: "Déconnexion", language: "Langue", update_success: "Profil mis à jour!", update_error: "Erreur de mise à jour.", success: "Succès", error: "Erreur", signout_confirm_title: "Déconnexion", signout_confirm_msg: "Êtes-vous sûr de vouloir vous déconnecter?", default_username: "Utilisateur", local_device: "Stocké sur cet appareil" },
    app: { go_to_date: "Date", task_deleted: "Supprimé", undo: "Annuler", overdue_tasks: "En retard", move_all_today: "À aujourd'hui", time_travel: "Voyage", timer: "Rappel", move_tomorrow: "Demain", schedule_tomorrow: "Pour demain", delete: "Supprimer", save: "Enregistrer", streak_days: "jours!", category: "Catégorie", schedule: "Programmer", permanent_notes: "Notes fixes", go_to_today: "Aujourd'hui", calendar: "Calendrier", write_before_forget: "N'oublie pas...", scheduled: "Prévu:", in_1_hour: "1 heure", tonight_21: "21:00", tomorrow_morning: "Matin", next_week: "Sem. pro.", uncompleted_tasks: "en attente", no_plan: "Pas d'excuses, passe à l'action.", write_to_dofo: "N'oublie pas...", scheduled_alert_title: "Prévu 📅", scheduled_alert_msg: "Tâche prévue", permanent_notes_placeholder: "N'oublie pas...", time_up: "Terminé", mins: "m", hours: "h", days: "j", today: "Aujourd'hui", yesterday: "Hier", tomorrow: "Demain", sync_connecting: "Connexion...", sync_loading_tasks: "Chargement des tâches...", sync_updating_notes: "Mise à jour des notes...", sync_finishing: "Presque prêt...", sync_done: "Prêt!", combo_2: "Bien!", combo_3: "Super!", combo_4: "Génial!", combo_5: "Incroyable!", combo_6: "Légendaire!", first_task_title: "Génial!", first_task_subtitle: "Premier pas franchi", notification_title: "dofo", notification_body: "Votre tâche vous attend ! 🚀", streak_count: "jours consécutifs !", streak_record: "Record : %{count} jours 🏆" },
    premium: { title: "dofo Premium", subtitle: "Libère tout ton potentiel.", task_limit_title: "Limite quotidienne atteinte", task_limit_msg: "Plan gratuit: 5 tâches par jour. Passe à Premium pour l'illimité.", reminder_title: "Fonction Premium", reminder_msg: "Les rappels sont Premium. Mets à niveau pour débloquer.", upgrade: "Passer à Premium", restore: "Restaurer l'achat", restore_not_found: "Aucun achat précédent trouvé.", feature_unlimited: "Tâches illimitées", feature_reminders: "Rappels intelligents", price: "4,99 € / mois", price_yearly: "39,99 € / an", save_badge: "33% éco.", monthly: "Mensuel", yearly: "Annuel", get_premium: "Obtenir Premium", already_premium: "Tu es Premium !", premium_badge: "PREMIUM", free_badge: "GRATUIT", go_premium: "Premium", manage_sub: "Gérer l'abonnement", manage_sub_hint: "Tu peux annuler à tout moment depuis ton store.", cancel_ios: "Annuler: Réglages → Apple ID → Abonnements.", cancel_android: "Annuler: Play Store → Compte → Abonnements.", legal_monthly: "4,99 €/mois. Facturé mensuellement.", legal_yearly: "39,99 €/an (33% éco.). Facturé annuellement.", legal_cancel: "Les abonnements se renouvellent automatiquement. Annuler 24h avant le renouvellement.", privacy: "Confidentialité", terms: "Conditions d'utilisation", past_reminder_error: "Impossible de programmer un rappel dans le passé.", daily_notif_title: "Prêt(e) à finir la journée en force ?", daily_notif_body: "Il te reste quelques tâches — règle-les et détends-toi !", weekly_notif_title: "Prêt(e) à planifier ta semaine ?", weekly_notif_body: "Une nouvelle semaine commence ! Fixe tes objectifs et rends-la mémorable." },
    welcome: { know_this: "Compris", promise: "Promis", give_up: "Abandonner", continue: "Continuer", coward_title: "Abandonner?", coward_msg: "Choisir la facilité.", coward_button: "Je n'abandonnerai pas",
        slide1_title: "Le temps file", slide1_subtitle: "Est-ce encore un jour 'Demain'? Retarde ta vie et tu ne seras jamais prêt.",
        slide2_title: "L'amère vérité", slide2_subtitle: "90% font des plans et arrêtent. Si l'abandon est plus facile, supprimez cette appli.",
        slide3_title: "Pas d'excuses", slide3_subtitle: "Personne ne te dorlotera. Construis une routine impitoyable et dépasse tes limites.",
        slide4_title: "Es-tu prêt(e)?", slide4_subtitle: "Sors de l'état d'esprit de perdant. Ne perds pas de temps si tu abandonnes."
    },
    quotes: {
        "0": "Aujourd'hui est à toi.", "1": "Chaque jour est un nouveau départ.", "2": "Petits pas, grand impact.", "3": "Continue.", "4": "Concentre-toi.",
        "5": "Tu en es capable.", "6": "La discipline est la liberté.", "7": "Réalise-le.", "8": "La constance est clé.", "9": "Commence maintenant."
    }
  }
};
